apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/DuarteDc/test-argo
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
